SET AUTOCOMMIT=1;
drop database videoclub;
CREATE DATABASE IF NOT EXISTS videoclub;

USE videoclub; 

CREATE TABLE GENERO (
	CodGenero 	INT(5) PRIMARY KEY, 
	Descripcion 	VARCHAR(15) );

CREATE TABLE ACTOR (
	CodActor	INT(5) PRIMARY KEY,
	Nombre 		VARCHAR(15) ); 

CREATE TABLE PELICULA (
	CodPeli			INT(5) PRIMARY KEY,
	Titulo			VARCHAR(30),
	CodGenero		INT(5),
	SegundaParte	INT(5),
	CodActor		INT(5),
	INDEX IDX_PELI_GEN (CodGenero),
	INDEX IDX_PELI_SEGP (SegundaParte),
	INDEX IDX_PELI_ACT (CodActor),
    FOREIGN KEY (CodGenero) REFERENCES GENERO(CodGenero),
    FOREIGN KEY (CodActor) REFERENCES ACTOR(CodActor)
);

ALTER TABLE PELICULA ADD CONSTRAINT FOREIGN KEY (SegundaParte) REFERENCES PELICULA(CodPeli);
CREATE TABLE INTERPRETADA (
	CodPeli 	INT(5), 
	CodActor	INT(5),
	PRIMARY KEY (CodPeli, CodActor), 
    INDEX IDX_PELIINTERPRETADA (CodPeli),
    INDEX IDX_ACTORINTERPRETADA (CodActor),
    FOREIGN KEY (CodPeli) REFERENCES PELICULA(CodPeli),
    FOREIGN KEY (CodActor) REFERENCES ACTOR(CodActor) );

CREATE TABLE COPIA (
	CodPeli 	INT(5),
	CodCopia 	INT(5),
	PRIMARY KEY (CodPeli, CodCopia),
	INDEX IDX_COPIA_PELI (CodPeli),
	FOREIGN KEY (CodPeli) REFERENCES PELICULA (CodPeli)  );

CREATE TABLE CLIENTE (
	DNI 		CHAR(10) PRIMARY KEY,
	Nombre 		VARCHAR(20), 
	Direccion	VARCHAR(20), 
	Telefono 	CHAR(9) );

CREATE TABLE PRESTAMO (
	CodPeli	INT(5), 
	CodCopia	INT(5), 
	Fecha		DATE, 
	DNI 		CHAR (10) ,
	PRIMARY KEY (CodPeli, CodCopia, Fecha),
    INDEX IDX_PRESTAMO_CLIENTE (DNI),
	FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI) );

CREATE TABLE FACTURA (
	CodFactura	INT(5)  PRIMARY KEY,
	Fecha		DATE, 
	Importe		DECIMAL (9,2), 
	DNI 		CHAR (10), 
	INDEX IDX_FACT_DNI (DNI),
	FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI) ); 

CREATE TABLE DETALLEFACTURA (
	CodFactura 	INT(5),
	LineaFactura	INT(5), 
	Descripcion	VARCHAR(15), 
	PrecioUnitaro	DECIMAL(9,2), 
	NumeroUnidades	INT(5),
	CONSTRAINT DETALL_PK PRIMARY KEY (CodFactura, LineaFactura),
	INDEX IDX_DETALL_FACT (CodFactura),
	FOREIGN KEY (CodFactura) REFERENCES FACTURA (CodFactura) ); 


INSERT INTO GENERO VALUES (1, 'Terror');
INSERT INTO GENERO VALUES (2, 'Comic');
INSERT INTO GENERO VALUES (3, 'Drama');

INSERT INTO ACTOR VALUES (1, 'Marie');
INSERT INTO ACTOR VALUES (2, 'Sam');
INSERT INTO ACTOR VALUES (3, 'Eva');

INSERT INTO PELICULA VALUES (1, 'Guardianes de la Galaxia', 2, NULL, 1);
INSERT INTO PELICULA VALUES (2, 'Doctor Strange', 2, NULL, 1);
INSERT INTO PELICULA VALUES (3, 'La niebla', 1, NULL, 3);
INSERT INTO PELICULA VALUES (4, 'Lo que el viento se llev�', 3, NULL, 2);
INSERT INTO PELICULA VALUES (5, 'Spiderman', 2, 1, 1);

INSERT INTO INTERPRETADA VALUES (1,1);
INSERT INTO INTERPRETADA VALUES (1,2);
INSERT INTO INTERPRETADA VALUES (2,1);
INSERT INTO INTERPRETADA VALUES (2,2);
INSERT INTO INTERPRETADA VALUES (3,1);
INSERT INTO INTERPRETADA VALUES (4,3);
INSERT INTO INTERPRETADA VALUES (5,3);

INSERT INTO COPIA VALUES (1, 1);
INSERT INTO COPIA VALUES (1, 2);
INSERT INTO COPIA VALUES (2, 1);
INSERT INTO COPIA VALUES (2, 2);
INSERT INTO COPIA VALUES (3, 1);
INSERT INTO COPIA VALUES (3, 2);
INSERT INTO COPIA VALUES (3, 3);
INSERT INTO COPIA VALUES (4, 1);
INSERT INTO COPIA VALUES (5, 1);

INSERT INTO CLIENTE VALUES ('011111111Z', 'Pedro Martinez Roy', NULL, '934444444');
INSERT INTO CLIENTE VALUES ('022222222R', 'Maria Casas Comas', NULL, '555666111');

INSERT INTO PRESTAMO VALUES (1, 1, '2017-02-25', '011111111Z');
INSERT INTO PRESTAMO VALUES (2, 1, '2017-03-01', '022222222R');
INSERT INTO PRESTAMO VALUES (1, 2, '2017-03-02', '022222222R');
INSERT INTO PRESTAMO VALUES (2, 2, '2017-03-02', '022222222R');
INSERT INTO PRESTAMO VALUES (3, 1, '2017-03-02', '022222222R');

INSERT INTO FACTURA VALUES (1, '2017-03-01', 5.50, '011111111Z');
INSERT INTO FACTURA VALUES (2, '2017-03-02', 4.50, '022222222R');
INSERT INTO FACTURA VALUES (3, '2017-03-06', 13.50, '022222222R');

INSERT INTO DETALLEFACTURA VALUES (1, 1, 'PELI1', 5.50, 1);
INSERT INTO DETALLEFACTURA VALUES (2, 1, 'PELI2', 4.50, 1);
INSERT INTO DETALLEFACTURA VALUES (3, 1, 'PELI1', 5.50, 1);
INSERT INTO DETALLEFACTURA VALUES (3, 2, 'PELI3', 4.50, 1);
INSERT INTO DETALLEFACTURA VALUES (3, 3, 'Cerveza', 3.50, 2);

